In [26]:
!pip install pandas
!pip install psycopg2

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [53]:
import pandas as pd
import psycopg2 
import decimal

In [27]:


data=pd.read_csv('items/new.csv')

In [28]:
# data.info()
dropped_col=data.drop(columns='contract')
data=dropped_col

In [32]:
data=data.dropna()
col=data.columns
trans_col=[x.replace('time (edt)', 'time_edt') for x in col]
data.columns=trans_col

In [ ]:
import psycopg2 
with open('secret.txt') as f:
    file = f.readlines()

secret = [x.split('=')[1].strip() for x in file]

def db_connection():
    try:
        conn=psycopg2.connect(
            database=secret[0],
            user=secret[1],
            host=secret[2],
            password=secret[3]
            port=secret[4]
    )
        print(f'Successfully connected to database')
    except Exception as e:
        print(f'connection failed ==>{e}')

    return conn

connection =db_connection()
cusor =connection.cursor()

In [35]:
data_metal=pd.read_csv('items/metal.csv')

In [51]:
data_metal

,Unnamed: 0,name,units,price,change,perc_change,time_edt
0,0,Gold (Comex),USD/t oz,"2,310.60",1.00,+0.04%,8:38 PM
1,1,Gold (Tokyo),JPY/g,"11,363.00",-209.00,-1.81%,8:28 PM
2,2,Gold Spot,USD/t oz,"2,302.60",-1.23,-0.05%,8:48 PM
3,3,Gold/Euro Spot,EUR/t oz,"2,145.79",-0.30,-0.01%,8:48 PM
4,4,Gold/British Pound Spot,GBP/t oz,"1,836.09",-1.83,-0.10%,8:48 PM
5,5,Gold/Japanese Yen Spot,JPY/t oz,"353,075.31",-892.97,-0.25%,8:48 PM
6,6,Gold/Indian Rupee Spot,INR/t oz,"192,181.13",143.59,+0.07%,8:48 PM
7,7,Silver (Comex),USD/t oz,26.88,0.05,+0.19%,8:38 PM
8,8,Silver (Tokyo),JPY/gram,134.00,-1.10,-0.81%,12:00 AM
9,9,Silver Spot,USD/t oz,26.67,-0.01,-0.05%,8:49 PM
10,10,Silver/Euro Spot,EUR/t oz,24.84,0.04,+0.17%,8:49 PM
11,11,Silver/British Pound Spot,GBP/t oz,21.26,-0.03,-0.13%,8:48 PM
12,12,Silver/Japanese Yen Spot,JPY/t oz,"4,087.46",-12.20,-0.30%,8:49 PM
13,13,Silver/Indian Rupee Spot,INR/t oz,"2,225.58",10.39,+0.47%,8:49 PM
14,14,Platinum Spot,USD/t oz,958.86,4.13,+0.43%,8:49 PM
15,15,Palladium Spot,USD/t oz,941.75,4.73,+0.50%,8:49 PM
16,16,Copper (Comex),USd/lb,450.30,1.85,+0.41%,8:38 PM
17,17,3Mo Copper (LME),USD/MT,"9,765.50",-130.00,-1.31%,12:00 AM
18,18,3Mo Aluminum (LME),USD/MT,"2,528.00",-49.50,-1.92%,12:00 AM
19,19,3Mo Zinc (LME),USD/MT,"2,886.00",5.00,+0.17%,12:00 AM
20,20,3Mo Tin (LME),USD/MT,"30,970.00",367.00,+1.20%,12:00 AM

In [57]:
#use this the method pd.to_numeric if the data or column contain NaN values.
# pd.to_numeric(data_metal['price'].str.replace(',','').astype(float),errors='coerce') 
# data_metal['price']=data_metal['price'].apply(lambda x: decimal.Decimal(x.replace(',', '')))
data_metal['price']=data_metal['price'].replace(',','').astype(float)

In [72]:
metaldf=pd.read_csv('items/metal_data.csv')

In [73]:
metaldf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   21 non-null     int64
 1   name         21 non-null     object
 2   units        21 non-null     object
 3   price        21 non-null     float64
 4   change       21 non-null     float64
 5   perc_change  21 non-null     float64
 6   time_edt     21 non-null     object
dtypes: float64(3), int64(1), object(3)
memory usage: 1.3+ KB

<class 'pandas.core.series.Series'>